version: '3'

services:
  rotten-potatoes:
    image: marcosadsj/rotten-potatoes:latest
    build:
      context: .
      dockerfile: Dockerfile 
    ports:
      - "5000:5000"
    container_name: rotten-potatoes
    environment:
      MONGODB_DB: admin
      MONGODB_HOST: mongodb
      MONGODB_PORT: 27017
      MONGODB_USERNAME: mongouser
      MONGODB_PASSWORD: mongopwd
    entrypoint: dockerize -wait tcp://mongodb:27017 -timeout 30s gunicorn --workers=3 --bind 0.0.0.0:5000 -c config.py app:app
    restart: always
    tty: true
    networks:
      - app-network
    depends_on:
      - mysql
  mongodb:
    image: mongo:5.0.5
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongouser
      MONGO_INITDB_ROOT_PASSWORD: mongopwd
    ports:
      - "27017:27017"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge